# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ordinare` gem.
# Please instead update this file by running `bin/tapioca gem ordinare`.

# source://ordinare//lib/ordinare/version.rb#1
module Ordinare
  private

  # source://ordinare//lib/ordinare.rb#9
  def hi; end

  # source://ordinare//lib/ordinare.rb#13
  def parse_args; end

  class << self
    # source://ordinare//lib/ordinare.rb#9
    def hi; end

    # source://ordinare//lib/ordinare.rb#13
    def parse_args; end
  end
end

# source://ordinare//lib/ordinare/check.rb#2
class Ordinare::Check
  # @return [Check] a new instance of Check
  #
  # source://ordinare//lib/ordinare/check.rb#7
  def initialize(path); end

  # @return [Boolean]
  #
  # source://ordinare//lib/ordinare/check.rb#11
  def gemfile_sorted?; end

  class << self
    # @return [Boolean]
    #
    # source://ordinare//lib/ordinare/check.rb#3
    def gemfile_sorted?(path = T.unsafe(nil)); end
  end
end

# source://ordinare//lib/ordinare/sort.rb#2
class Ordinare::Sort
  # @return [Sort] a new instance of Sort
  #
  # source://ordinare//lib/ordinare/sort.rb#11
  def initialize(overwrite, path); end

  # source://ordinare//lib/ordinare/sort.rb#29
  def sort_content(content); end

  # source://ordinare//lib/ordinare/sort.rb#17
  def sort_gemfile; end

  private

  # source://ordinare//lib/ordinare/sort.rb#42
  def find_ranges_of_gems(content); end

  # source://ordinare//lib/ordinare/sort.rb#77
  def write_to_a_file(content); end

  class << self
    # source://ordinare//lib/ordinare/sort.rb#7
    def sort_content(path = T.unsafe(nil), content); end

    # source://ordinare//lib/ordinare/sort.rb#3
    def sort_gemfile(overwrite = T.unsafe(nil), path = T.unsafe(nil)); end
  end
end

# source://ordinare//lib/ordinare/version.rb#2
Ordinare::VERSION = T.let(T.unsafe(nil), String)
