name: Ruby

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: check Gem order
        run: bundle exec ordinare --check
      - name: Run RuboCop
        run: bundle exec rubocop -DESP
    strategy:
      matrix:
        ruby:
          - "3.1.2"
          - "3.2.2"

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Check Sorbet shims
        run: bundle exec tapioca check-shims
      - name: Check types
        run: bundle exec spoom tc
    strategy:
      matrix:
        ruby:
          - "3.1.2"
          - "3.2.2"

  test:
    runs-on: ubuntu-latest
    name: Test (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec -f d
    strategy:
      matrix:
        ruby:
          - "3.1.2"
          - "3.2.2"

  docs:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    permissions:
      contents: write
      pages: write
      id-token: write
    strategy:
      matrix:
        ruby:
          - "3.1.2"
          - "3.2.2"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run yard
        run: bundle exec yardoc -o doc/ --plugin yard-sorbet
      - name: Deploy documentations to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
          destination_dir: docs
      - name: Deploy SimpleCov Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          destination_dir: coverage
