name: Ruby

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Check Gem order
        run: bundle exec ordinare --check
      - name: Run RuboCop
        run: bundle exec rubocop -DESP
    strategy:
      matrix:
        ruby:
          - "3.1.2"
          - "3.2.6"
          - "3.3.6"
          - "3.4.1"

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Check Sorbet shims
        run: bundle exec tapioca check-shims
      - name: Check types
        run: bundle exec spoom srb tc
    strategy:
      matrix:
        ruby:
          - "3.1.2"
          - "3.2.6"
          - "3.3.6"
          - "3.4.1"

  test:
    runs-on: ubuntu-latest
    name: Test (Ruby ${{ matrix.ruby }})
    needs:
      - lint
      - typecheck
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec -f d
    strategy:
      matrix:
        ruby:
          - "3.1.2"
          - "3.2.6"
          - "3.3.6"
          - "3.4.1"
