name: Ruby

on:
  push:
    tags:
      - "v*"

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Documentation
    if: contains(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Run yard
        run: bundle exec yardoc -o doc/ --plugin yard-sorbet
      - name: Deploy documentations to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
          destination_dir: docs
      - name: Deploy SimpleCov Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          destination_dir: coverage

  release:
    runs-on: ubuntu-latest
    name: Release
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Build Gem
        run: rake build

      - uses: step-security/wait-for-secrets@v1
        id: input-otp
        with:
          secrets: |
            RUBYGEMS_OTP:
              name: 'RubyGems OTP'

      - name: Publish to RubyGems
        uses: cadwallion/publish-rubygems-action@v1.1.0
        env:
          GEM_HOST_OTP_CODE: ${{ steps.input-otp.outputs.RUBYGEMS_OTP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          RELEASE_COMMAND: rake release
